const KEY='carnetSportV1', LIB='carnetSportExercisesV1';
let db=JSON.parse(localStorage.getItem(KEY)||'[]');
let library=JSON.parse(localStorage.getItem(LIB)||'null')||['Développé couché','Développé incliné haltères','Squat','Presse à cuisses','Soulevé de terre','Tractions','Tirage vertical','Rowing','Développé militaire','Élévations latérales','Curl biceps','Extension triceps','Fentes','Leg curl','Leg extension','Mollets'];
let current=null,timer=null,remaining=180,restDuration=180;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify(db));localStorage.setItem(LIB,JSON.stringify(library));renderAll()}
function dateFR(s){if(!s)return '—';let [y,m,d]=s.split('-');return d+'/'+m+'/'+y}
function todayISO(){let d=new Date();return new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())).toISOString().slice(0,10)}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));renderAll()}
function start(){current={id:Date.now(),date:todayISO(),name:'',exercises:[]};$('wDate').value=current.date;$('wName').value='';$('workoutExercises').innerHTML='';show('workout')}
function addExercise(name=''){let e={id:Date.now()+Math.random(),name:name,sets:[{weight:'',reps:''}]};current.exercises.push(e);renderWorkout()}
function renderWorkout(){if(!current)return;$('wDate').value=current.date;$('wName').value=current.name;$('workoutExercises').innerHTML=current.exercises.map((e,ei)=>`<div class="card"><div class="between"><span class="exercise-title">${esc(e.name||'Exercice')}</span><button class="btn danger tiny" onclick="removeExercise(${ei})">Suppr.</button></div>${e.name?`<div class="set-head"><span>#</span><span>Poids (kg)</span><span>Rép.</span><span></span></div>${e.sets.map((s,si)=>`<div class="set-row"><span class="setno">${si+1}</span><input class="input tiny" type="number" min="0" step=".5" value="${esc(s.weight)}" onchange="updSet(${ei},${si},'weight',this.value)" placeholder="0"><input class="input tiny" type="number" min="0" step="1" value="${esc(s.reps)}" onchange="updSet(${ei},${si},'reps',this.value)" placeholder="0"><button class="btn secondary tiny" onclick="removeSet(${ei},${si})">×</button></div>`).join('')}<button class="btn secondary tiny mt" onclick="addSet(${ei})">＋ Série</button>`:`<button class="btn secondary" onclick="chooseExercise(${ei})">Choisir l’exercice</button>`}</div>`).join('')}
function removeExercise(i){current.exercises.splice(i,1);renderWorkout()}
function addSet(i){current.exercises[i].sets.push({weight:'',reps:''});renderWorkout()}
function removeSet(i,s){if(current.exercises[i].sets.length>1)current.exercises[i].sets.splice(s,1);renderWorkout()}
function updSet(i,s,k,v){current.exercises[i].sets[s][k]=v}
function chooseExercise(i){current.chooseIndex=i;openModal()}
function openModal(){$('modal').classList.remove('hidden');$('exerciseSearch').value='';renderOptions()}
function renderOptions(){let q=$('exerciseSearch').value.toLowerCase();$('exerciseOptions').innerHTML=library.filter(x=>x.toLowerCase().includes(q)).map(x=>`<div class="exercise-option"><span>${esc(x)}</span><button class="btn primary tiny" onclick="pickExercise('${escAttr(x)}')">Choisir</button></div>`).join('')||'<div class="empty">Aucun exercice trouvé.</div>'}
function pickExercise(name){current.exercises[current.chooseIndex].name=name;$('modal').classList.add('hidden');renderWorkout()}
function saveWorkout(){current.date=$('wDate').value;current.name=$('wName').value.trim()||'Séance';current.exercises=current.exercises.filter(e=>e.name);if(!current.date||!current.exercises.length){alert('Ajoute une date et au moins un exercice.');return}db.unshift(JSON.parse(JSON.stringify(current)));save();current=null;show('history')}
function renderAll(){let sets=db.reduce((n,w)=>n+w.exercises.reduce((a,e)=>a+e.sets.filter(s=>s.weight!==''||s.reps!=='').length,0),0),ex=db.reduce((n,w)=>n+w.exercises.length,0),vol=db.reduce((n,w)=>n+w.exercises.reduce((a,e)=>a+e.sets.reduce((b,s)=>b+(+s.weight||0)*(+s.reps||0),0),0),0);$('today').textContent=new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('statSessions').textContent=db.length;$('statExercises').textContent=ex;$('statSets').textContent=sets;$('statVolume').textContent=Math.round(vol).toLocaleString('fr-FR')+' kg';let last=db[0];$('lastDate').textContent=last?dateFR(last.date):'—';$('lastWorkout').innerHTML=last?`<b>${esc(last.name)}</b><br>${last.exercises.map(e=>esc(e.name)).join(' · ')}`:'Aucune séance enregistrée.';renderHistory();renderProgress();renderLibrary()}
function renderHistory(){$('historyList').innerHTML=db.length?db.map((w,i)=>`<div class="history-item"><div class="between"><div><div class="sub">SÉANCE</div><b style="font-size:17px">${esc(w.name||'Séance')}</b><div class="sub">${dateFR(w.date)} · ${w.exercises.length} exercice(s)</div></div><button class="btn danger tiny" onclick="deleteWorkout(${i})">Suppr.</button></div><div class="small mt">${w.exercises.map(e=>`<b>${esc(e.name)}</b> : ${e.sets.filter(s=>s.weight!==''||s.reps!=='').map(s=>`${esc(s.weight||'—')} kg × ${esc(s.reps||'—')}`).join(', ')||'aucune série'}`).join('<br>')}</div></div>`).join(''):'<div class="empty">Ton historique apparaîtra ici après ta première séance.</div>'}
function deleteWorkout(i){if(confirm('Supprimer cette séance ?')){db.splice(i,1);save()}}
function renderProgress(){let map={};db.forEach(w=>w.exercises.forEach(e=>e.sets.forEach(s=>{let wt=+s.weight||0,r=+s.reps||0;if(!map[e.name])map[e.name]={best:0,volume:0,sets:0};map[e.name].best=Math.max(map[e.name].best,wt);map[e.name].volume+=wt*r;map[e.name].sets++})));let names=Object.keys(map);$('progressList').innerHTML=names.length?names.map(n=>`<div class="history-item"><b>${esc(n)}</b><div class="grid mt"><div class="stat"><span class="label">Charge max</span><b>${map[n].best} kg</b></div><div class="stat"><span class="label">Volume</span><b>${Math.round(map[n].volume).toLocaleString('fr-FR')} kg</b></div></div></div>`).join(''):'<div class="empty">Enregistre quelques séances pour voir ta progression.</div>'}
function renderLibrary(){$('libraryList').innerHTML=library.map((x,i)=>`<div class="between" style="padding:9px 0;border-bottom:1px solid var(--line)"><span>${esc(x)}</span><button class="btn danger tiny" onclick="deleteLibrary(${i})">×</button></div>`).join('')}
function deleteLibrary(i){if(confirm('Supprimer cet exercice de la bibliothèque ?')){library.splice(i,1);save()}}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function escAttr(x){return esc(x).replace(/`/g,'&#96;')}
function startRest(seconds){if(timer)clearInterval(timer);restDuration=seconds;remaining=seconds;$('timerBox').classList.remove('hidden');$('timerLabel').textContent='Repos de '+(seconds/60)+' min';renderTimer();timer=setInterval(()=>{remaining--;renderTimer();if(remaining<=0){clearInterval(timer);timer=null;remaining=0;renderTimer();$('timerLabel').textContent='Repos terminé';}},1000)}
function stopRest(){if(timer)clearInterval(timer);timer=null;$('timerBox').classList.add('hidden')}
function renderTimer(){$('timer').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');$('timerBar').style.width=(100-(remaining/restDuration*100))+'%'}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
$('startBtn').onclick=start;$('addExercise').onclick=()=>{addExercise();if(current.exercises.length)chooseExercise(current.exercises.length-1)};$('saveWorkout').onclick=saveWorkout;$('cancelWorkout').onclick=()=>{current=null;stopRest();show('home')};$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('exerciseSearch').oninput=renderOptions;$('rest3').onclick=()=>startRest(180);$('rest5').onclick=()=>startRest(300);$('timerStop').onclick=stopRest;
$('newExercise').onclick=()=>{let n=prompt('Nom du nouvel exercice :');if(n&&n.trim()){library.push(n.trim());library=[...new Set(library)].sort((a,b)=>a.localeCompare(b));save()}};
$('clearAll').onclick=()=>{if(db.length&&confirm('Supprimer tout l’historique ?')){db=[];save()}};
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');document.documentElement.style.setProperty('--bg',document.body.classList.contains('dark')?'#0b1220':'#f4f5f7');document.documentElement.style.setProperty('--card',document.body.classList.contains('dark')?'#111827':'#fff');document.documentElement.style.setProperty('--text',document.body.classList.contains('dark')?'#f8fafc':'#111827');document.documentElement.style.setProperty('--line',document.body.classList.contains('dark')?'#253044':'#e5e7eb')};
renderAll();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
